language: c
sudo: false
git:
  submodules: false
cache:
  directories:
  - "$HOME/.cabal/packages"
  - "$HOME/.cabal/store"
before_cache:
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
matrix:
  include:
  - compiler: ghc-8.0.2
    addons:
      apt:
        packages:
        - ghc-ppa-tools
        - cabal-install-head
        - ghc-8.0.2
        - alex
        - happy
        sources:
        - hvr-ghc
  - compiler: ghc-8.2.1
    addons:
      apt:
        packages:
        - ghc-ppa-tools
        - cabal-install-head
        - ghc-8.2.1
        - alex
        - happy
        sources:
        - hvr-ghc
before_install:
- HC=${CC}
- unset CC
- PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH
- PKGNAME='DeploymentTests'
install:
- cabal --version
- echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null ||
  echo '?')]"
- BENCH=${BENCH---enable-benchmarks}
- TEST=${TEST---enable-tests}
- travis_retry cabal update -v
- sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
- rm -fv cabal.project.local
- 'echo ''packages: .'' > cabal.project'
- rm -f cabal.project.freeze
- cabal new-build -w ${HC} ${TEST} ${BENCH} --dep -j2 all
- cabal new-build -w ${HC} --disable-tests --disable-benchmarks --dep -j2 all
script:
- if [ -f configure.ac ]; then autoreconf -i; fi
- rm -rf .ghc.environment.* dist/
- cabal sdist
- cd dist/
- SRCTAR=(${PKGNAME}-*.tar.gz)
- SRC_BASENAME="${SRCTAR/%.tar.gz}"
- tar -xvf "./$SRC_BASENAME.tar.gz"
- cd "$SRC_BASENAME/"
- rm -fv cabal.project.local
- 'echo ''packages: .'' > cabal.project'
- rm -f cabal.project.freeze
- cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
- cabal new-build -w ${HC} ${TEST} ${BENCH} all
- if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} all; fi
# This is all part of the deployment process
- bash .travis-prepare-release.sh
deploy:
  provider: releases
  file: test.tgz
  skip_cleanup: true
  overwrite: true
  #  on:
  #    tags: true
  #    all_branches: true
  on:
      branches:
          only:
              - master
  api_key:
    secure: "tGYHqgCyt0TwpZytYClyW3UTBmYg+OOFEIRj/YUFm8Y2U8OrxmBcO1kPd7Z9L0zDTfX2FUohk+XtR1TlO0fzIBj9So1alJiWq1ziLLHjfgVzVm3ZBpTIQNO+CfxGQWu91fgcnnI9ZnuJLL3kObTHvnm6oW0fldEcFCme+ymFedu5VRciNtSrgpqg1VnghfzgVZ1L+l0ZgTbbOzvBb0L7JcR4sIH6RbMgzOfxHgtGe5ZX587wUZRmCq8AzhM+kkZ9PmF2xy4shVgT7iYOUwRKlaB6o8OAV/2RLhhGrt8o37CIlU+WZjWvrrs5Fx5sQMZG9S6AjmZ+butnuxw15+zo0mIPcyIC5MaGptSvC7XZPyfxeWjT206fiIRxCIS6z25MWspPKk0X4+fdDlQgKHCHjz3uVkxjA1asImYYEbDpsmvxPkyhO7yuknrFf+7WBQpD7eehPvnmYT4vq5QH8pXhe0nZySsU+a629SYhrBzFFamp10mATxJ22A/a+eceV2DPBSsTNYI/lySc3px8F8ciRf3xoChdpAfvtpaLjbImpcIgIdqxn3SdKEokC7I0W8wIDbsn4lvCLPGVyuT44NgrH0S1ky29FN02uM5Iq+kfUB04HSsaUsAibhu2/ujykVKfCEyRvL7j4tAbNx+nPnqZfC+t1b3aOFnmDGdzwr1J2QI="


